name: Unda APK ya Android

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Vuta Kodi
      uses: actions/checkout@v4

    - name: Weka Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Weka Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Weka Zana za Mfumo na Buildozer
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblldb-dev libffi-dev libreadline-dev libncurses5-dev libncursesw5-dev liblzma-dev cmake libonig-dev unzip zip git ccache autoconf libtool pkg-config
        python -m pip install --upgrade pip setuptools wheel
        pip install Cython==0.29.33 buildozer

    - name: Unda APK ya Android
      run: |
        yes | buildozer -v android debug

    - name: Hifadhi APK
      uses: actions/upload-artifact@v4
      with:
        name: otomesheni-app-debug
        path: bin/*.apk
